spring:
  profiles:
    active: local

---
spring:
  profiles: local
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

---
spring:
  profiles: prod
  datasource:
    url: ${MYSQL_HOST}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  sendgrid:
    api-key: ${SENDGRID_API_KEY}

baseUrl: http://nfs.jaehoon.kim/signup/confirm

server:
  port: 8080
